### ISSUE TITLE
java.lang.BootstrapMethodError: Exception from call site #2 bootstrap method

### ISSUE THREAD

**Issue by jayeshbabuav** [suiko1984/geofirestore-android#8]
For me, `setLocation()` and `getLocation()`
works fine.but, when i use the following code, `GeoQuery geoQuery = geoFire.queryAtLocation(new GeoLocation(location.latitude, location.longitude), 20);`, the following exception occurs:

```
java.lang.BootstrapMethodError: Exception from call site #2 bootstrap method
        at com.koalap.geofirestore.GeoQuery.<init>(GeoQuery.java:68)
        at com.koalap.geofirestore.GeoFire.queryAtLocation(GeoFire.java:256)
        at in.hashcoder.dishyumm.Utils.MainPostAdapter$8$1.onLocationResult(MainPostAdapter.java:217)
        at com.koalap.geofirestore.GeoFire$LocationValueEventListener.onComplete(GeoFire.java:90)
        at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6986)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at com.koalap.geofirestore.GeoQuery.<init>(GeoQuery.java:68) 
        at com.koalap.geofirestore.GeoFire.queryAtLocation(GeoFire.java:256) 
        at in.hashcoder.dishyumm.Utils.MainPostAdapter$8$1.onLocationResult(MainPostAdapter.java:217) 
        at com.koalap.geofirestore.GeoFire$LocationValueEventListener.onComplete(GeoFire.java:90) 
        at com.google.android.gms.tasks.zzj.run(Unknown Source:4) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6986) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445) 
```

**Comment by suiko1984** [comment]
Hi @jayeshbabuav , what version of firestore are you using? I will update a new fix in the coming update. Thanks!
